
import { Component, ChangeDetectionStrategy, signal, computed, effect, inject, ViewChild, ElementRef, OnInit, WritableSignal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { LicenseService } from '../../services/license.service';
import { PersistenceService } from '../../services/persistence.service';
import { BetParsingService } from '../../services/bet-parsing.service';
import { VoiceRecognitionService } from '../../services/voice-recognition.service';
import { ReportViewerComponent } from '../report-viewer/report-viewer.component';
import { UserGuideComponent } from '../user-guide/user-guide.component';
import { ForwardingModalComponent, Assignments } from '../forwarding-modal/forwarding-modal.component';
import { Agent, UpperBookie, Report, GridCell, BetDetail, VoucherSettings } from '../../models/app.models';
import { SummaryCardComponent } from '../summary-card/summary-card.component';

// --- Interfaces ---
type LotteryType = '2D' | '3D';
interface Bet { number: string; amount: number; }
interface HistoryEntry { id: string; input: string; source: string; mode?: string; rawBets?: Bet[]; }
interface AcceptedSubmission { agent: string; content: string; timestamp: Date; total: number; }

interface AgentPayoutInfo {
  name: string;
  totalSales: number;
  commissionRate: number;
  commissionAmount: number;
  netSales: number;
  
  // New granular win details
  totalWinBetAmount: number; // The sum of betting amount on winning number (regardless of limit)
  totalWinAmount: number;    // Total Win Amount (Bet * Rate)
  
  overLimitWinBetAmount: number; // The sum of betting amount that was cut/over limit
  overLimitWinAmount: number;    // Win amount generated by Over Limit bets (Pass to upper/Reject)
  
  heldWinBetAmount: number;   // The sum of betting amount that was actually Held
  payout: number;             // The Actual Payout (Held Win Amount)
  
  finalBalance: number;
  individualBets: number[]; // List of specific bet amounts for display (e.g. 100, 200)
}

interface PayoutDetails {
  winningNumber: string;
  totalBet: number;
  totalHeldBet: number;
  totalHeldPayout: number;
  totalOverLimitBet: number;
  totalOverLimitPayout: number;
  agentPayouts: AgentPayoutInfo[];
  otherPayouts: AgentPayoutInfo[]; 
}

interface AgentWithPerformance extends Agent {
  totalSales: number;
}
type OverLimitListItem = { number: string; overLimitAmount: number };
interface ProfitOptimizerSuggestion {
  topNumbers: GridCell[];
  suggestedHoldingIncrease: number;
  potentialProfitIncrease: number;
}
interface InboxResult {
  agent: string;
  totalAccepted: number;
  rejectedText?: string;
  isAllAccepted: boolean;
}

interface VoucherData {
  items: { number: string; amount: number }[];
  totalAmount: number;
  totalCount: number;
  date: string;
  time: string;
  currency: string;
  settings?: VoucherSettings; // Include settings in data for the modal
}

interface RiskAnalysis {
  number: string;
  totalHeld: number;
  estimatedPayout: number;
  netProfitLoss: number; // Positive = Profit, Negative = Loss
}

interface AppState {
    betHistory: HistoryEntry[];
    defaultLimit: number;
    payoutRate: number;
    commissionToPay: number;
    commissionFromUpperBookie: number;
    agentCommissionFromBookie: number;
    individualLimits: Map<string, number>;
    myAgentName: string;
    agentProfiles: string[];
    myMiddleBookieName: string;
    myMainBookieName: string;
    session?: 'morning' | 'evening';
    drawDate?: string;
    userInput: string;
    voucherSettings?: VoucherSettings;
}

@Component({
  selector: 'app-code-analyzer',
  templateUrl: './code-analyzer.component.html',
  styleUrls: ['./code-analyzer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, ReportViewerComponent, UserGuideComponent, ForwardingModalComponent, SummaryCardComponent],
  host: {
    '(window:keydown)': 'handleKeyboardEvents($event)',
    '(window:beforeunload)': 'onBeforeUnload($event)'
  }
})
export class CodeAnalyzerComponent implements OnInit {
  licenseService = inject(LicenseService);
  persistenceService = inject(PersistenceService);
  betParsingService = inject(BetParsingService);
  voiceService = inject(VoiceRecognitionService);

  // --- Child Elements ---
  @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;
  @ViewChild('mainBetInput') mainBetInput!: ElementRef<HTMLTextAreaElement>;


  // --- Core State ---
  lotteryType = signal<LotteryType>('2D');
  modes = ['အေးဂျင့်', 'အလယ်ဒိုင်', 'ဒိုင်ကြီး'];
  activeMode = signal(this.modes[0]);
  
  appState = signal<Record<LotteryType, AppState>>({
    '2D': this.createInitialState('2D'),
    '3D': this.createInitialState('3D')
  });

  isDataLoaded = signal(false);
  showReports = signal(false);
  showUserGuide = signal(false);
  showClearAllConfirmation = signal(false);
  isOnline = signal(navigator.onLine);
  currencies: Array<'K' | '฿' | '¥'> = ['K', '฿', '¥'];
  currencySymbol = signal<'K' | '฿' | '¥'>('K');
  
  // --- New Feature States ---
  showHeatmap = signal(false);
  showRiskModal = signal(false);
  isPanicMode = signal(false);
  panicInput = signal('');
  showVoucherSettings = signal(false);
  
  // Default Voucher Settings
  voucherSettings = computed(() => {
      const state = this.appState()[this.lotteryType()];
      return state.voucherSettings || {
          headerText: this.bookieName(),
          footerText: 'ကံကောင်းပါစေ',
          fontSize: 'medium',
          showDateTime: true
      } as VoucherSettings;
  });

  // --- Relationship Management State (Shared) ---
  upperBookies = signal<UpperBookie[]>([]);
  newUpperBookieName = signal('');
  newUpperBookieCommission = signal(10);
  
  agentUpperBookies = signal<{name: string}[]>([]);
  newAgentUpperBookieName = signal('');
  
  // -- Agent State (Separated by Mode) --
  middleBookieAgents = signal<Agent[]>([]);
  mainBookieAgents = signal<Agent[]>([]);
  
  agents = computed(() => {
      if (this.activeMode() === 'အလယ်ဒိုင်') return this.middleBookieAgents();
      if (this.activeMode() === 'ဒိုင်ကြီး') return this.mainBookieAgents();
      return []; 
  });

  newAgentName = signal('');
  newAgentCommission = signal(5);
  agentSortBy = signal<'name' | 'sales'>('sales');

  // --- Workflow State ---
  inboxInput = signal('');
  selectedAgentForInbox = signal<string | null>(null);
  pendingInboxConfirmation = signal<{ 
    safeBets: Bet[];
    overLimitBets: Bet[];
    agent: string;
    originalInput: string;
  } | null>(null);
  acceptedSubmissions = signal<AcceptedSubmission[]>([]);
  lastInboxResult = signal<InboxResult | null>(null);

  showPayoutModal = signal(false);
  winningNumber = signal('');
  payoutDetails = signal<PayoutDetails | null>(null);
  
  pendingSubmissions = signal<string[]>([]);
  showSubmissionModal = signal(false);
  submissionText = signal('');
  
  // --- Voucher Modal State ---
  showVoucherModal = signal(false);
  voucherData = signal<VoucherData | null>(null);

  acknowledgedOverLimits = signal<Map<string, number>>(new Map());
  
  // --- State for Middle Bookie Over-Limit Management ---
  rejectedOverLimits = signal<Set<string>>(new Set<string>());
  acknowledgedHeldOverLimits = signal<Map<string, number>>(new Map());
  isForwardingModalOpen = signal(false);

  // --- Bet Detail Editing State ---
  showBetDetailModal = signal(false);
  selectedNumberForDetail = signal<string | null>(null);

  // --- Limit Management State ---
  showLimitManagementModal = signal(false);
  limitManageNumber = signal('');
  limitManageAmount = signal<number>(0);

  // --- Messaging State ---
  confirmationMessage = signal('');
  statusMessage = signal('');
  
  // --- Profit Optimizer State ---
  profitOptimizerSuggestion = signal<ProfitOptimizerSuggestion | null>(null);
  suggestionAppliedRecently = signal(false);

  // --- 3D Specific State ---
  search3DTerm = signal('');

  // --- Proxy Computed Signals for Active State ---
  betHistory = computed(() => this.appState()[this.lotteryType()].betHistory);
  defaultLimit = computed(() => this.appState()[this.lotteryType()].defaultLimit);
  payoutRate = computed(() => this.appState()[this.lotteryType()].payoutRate);
  commissionToPay = computed(() => this.appState()[this.lotteryType()].commissionToPay);
  commissionFromUpperBookie = computed(() => this.appState()[this.lotteryType()].commissionFromUpperBookie);
  agentCommissionFromBookie = computed(() => this.appState()[this.lotteryType()].agentCommissionFromBookie);
  individualLimits = computed(() => this.appState()[this.lotteryType()].individualLimits);
  
  bookieName = computed(() => {
      const state = this.appState()[this.lotteryType()];
      switch (this.activeMode()) {
          case 'အေးဂျင့်': return state.myAgentName;
          case 'အလယ်ဒိုင်': return state.myMiddleBookieName;
          case 'ဒိုင်ကြီး': return state.myMainBookieName;
          default: return state.myMainBookieName;
      }
  });

  agentProfiles = computed(() => this.appState()[this.lotteryType()].agentProfiles || []);

  session = computed(() => this.appState()['2D'].session!);
  drawDate = computed(() => this.appState()['3D'].drawDate!);
  userInput = computed(() => this.appState()[this.lotteryType()].userInput);

  // --- Computed Signals (Logic) ---
  lotteryData = computed<Map<string, BetDetail[]>>(() => {
    const data = new Map<string, BetDetail[]>();
    const currentMode = this.activeMode();
    const history = this.betHistory().filter(h => {
        const entryMode = h.mode || 'ဒိုင်ကြီး';
        return entryMode === currentMode;
    });

    for (const entry of history) {
      const parsedBets = this.betParsingService.parseRaw(entry.input, this.lotteryType());
      parsedBets.forEach(bet => {
        const existingBets = data.get(bet.number) || [];
        const newBet: BetDetail = { id: crypto.randomUUID(), amount: bet.amount, source: entry.source, historyEntryId: entry.id };
        data.set(bet.number, [...existingBets, newBet]);
      });
    }
    return data;
  });

  // --- Computed Signals (UI) ---
  recentHistory = computed(() => {
      const currentMode = this.activeMode();
      return this.betHistory()
        .filter(h => {
             const entryMode = h.mode || 'ဒိုင်ကြီး';
             return entryMode === currentMode;
        })
        .slice(-20)
        .reverse();
  });

  // 2D Grid
  gridCells = computed<GridCell[]>(() => {
    if (this.lotteryType() !== '2D') return [];
    const data = this.lotteryData();
    const cells: GridCell[] = [];
    const currentIndLimits = this.individualLimits();
    const currentDefLimit = this.defaultLimit();

    for (let i = 0; i < 100; i++) {
      const numberStr = i.toString().padStart(2, '0');
      const breakdown = data.get(numberStr) || [];
      const amount = breakdown.reduce((sum, bet) => sum + bet.amount, 0);
      
      const hasCustomLimit = (this.activeMode() === 'ဒိုင်ကြီး' || this.activeMode() === 'အလယ်ဒိုင်') && currentIndLimits.has(numberStr);
      const limit = hasCustomLimit ? currentIndLimits.get(numberStr)! : currentDefLimit;
      
      const isOverLimit = amount > limit;
      const overLimitAmount = isOverLimit ? amount - limit : 0;

      const amounts = breakdown.map(b => b.amount);
      const betsString = amounts.length > 0 ? (this.activeMode() === 'အေးဂျင့်' ? amounts.join(', ') : `(${amounts.join(', ')})`) : '';
      const betsTooltip = breakdown.map(b => `${b.source}: ${b.amount}`).join('; ');

      cells.push({ number: numberStr, amount, isOverLimit, hasCustomLimit, breakdown, betsString, betsTooltip, overLimitAmount, limit });
    }
    return cells;
  });

  // 3D List
  listItems = computed<GridCell[]>(() => {
      if (this.lotteryType() !== '3D') return [];
      const data = this.lotteryData();
      const items: GridCell[] = [];
      const currentIndLimits = this.individualLimits();
      const currentDefLimit = this.defaultLimit();

      for (const [numberStr, breakdown] of data.entries()) {
          const amount = breakdown.reduce((sum, bet) => sum + bet.amount, 0);
          if (amount === 0) continue;
          
          const hasCustomLimit = (this.activeMode() === 'ဒိုင်ကြီး' || this.activeMode() === 'အလယ်ဒိုင်') && currentIndLimits.has(numberStr);
          const limit = hasCustomLimit ? currentIndLimits.get(numberStr)! : currentDefLimit;

          const isOverLimit = amount > limit;
          const overLimitAmount = isOverLimit ? amount - limit : 0;
          const amounts = breakdown.map(b => b.amount);
          const betsString = amounts.length > 0 ? `(${amounts.join(', ')})` : '';
          const betsTooltip = breakdown.map(b => `${b.source}: ${b.amount}`).join('; ');
          
          items.push({ number: numberStr, amount, isOverLimit, hasCustomLimit, breakdown, betsString, betsTooltip, overLimitAmount, limit });
      }
      return items.sort((a, b) => a.number.localeCompare(b.number));
  });

  filteredListItems = computed(() => {
      const term = this.search3DTerm().toLowerCase();
      if (!term) return this.listItems();
      return this.listItems().filter(item => item.number.includes(term));
  });
  
  customLimitsList = computed(() => {
      const limits = this.individualLimits();
      return Array.from(limits.entries())
        .map(([number, limit]) => ({ number, limit }))
        .sort((a, b) => a.number.localeCompare(b.number));
  });

  totalBetAmount = computed<number>(() => {
    const data = this.lotteryType() === '2D' ? this.gridCells() : this.listItems();
    return data.reduce((sum, cell) => sum + cell.amount, 0);
  });

  overLimitCells = computed(() => {
    const data = this.lotteryType() === '2D' ? this.gridCells() : this.listItems();
    return data.filter(cell => cell.isOverLimit)
  });

  betsForDetailModal = computed<BetDetail[]>(() => {
    const selectedNumber = this.selectedNumberForDetail();
    if (!selectedNumber) return [];
    return this.lotteryData().get(selectedNumber) || [];
  });

  // --- New Over-Limit List Computations ---
  private filterAcknowledged(list: GridCell[], acknowledgedMap: Map<string, number>): OverLimitListItem[] {
      const displayed: OverLimitListItem[] = [];
      for (const cell of list) {
          const acknowledgedAmount = acknowledgedMap.get(cell.number) || 0;
          const newOverLimitPortion = cell.overLimitAmount - acknowledgedAmount;
          if (newOverLimitPortion > 0) {
              displayed.push({ number: cell.number, overLimitAmount: newOverLimitPortion });
          }
      }
      return displayed;
  }
  
  displayedOverLimitNumbers = computed<OverLimitListItem[]>(() => {
    if (this.activeMode() === 'အေးဂျင့်') return [];
    return this.filterAcknowledged(this.overLimitCells(), this.acknowledgedOverLimits());
  });

  forwardableOverLimitNumbers = computed<OverLimitListItem[]>(() => {
      if (this.activeMode() !== 'အလယ်ဒိုင်') return [];
      const nonRejected = this.overLimitCells().filter(cell => !this.rejectedOverLimits().has(cell.number));
      return this.filterAcknowledged(nonRejected, this.acknowledgedOverLimits());
  });

  forwardableNumbersForModal = computed(() => {
    return this.forwardableOverLimitNumbers().map(item => ({ number: item.number, amount: item.overLimitAmount }));
  });

  heldOverLimitNumbers = computed<OverLimitListItem[]>(() => {
      if (this.activeMode() !== 'အလယ်ဒိုင်') return [];
      const rejected = this.overLimitCells().filter(cell => this.rejectedOverLimits().has(cell.number));
      return this.filterAcknowledged(rejected, this.acknowledgedHeldOverLimits());
  });

  // --- Financial Computations ---
  totalOverLimitAmount = computed<number>(() => this.overLimitCells().reduce((sum, cell) => sum + cell.overLimitAmount, 0));

  forwardableOverLimitAmount = computed<number>(() => {
    if (this.activeMode() !== 'အလယ်ဒိုင်') return 0;
    return this.overLimitCells()
        .filter(cell => !this.rejectedOverLimits().has(cell.number))
        .reduce((sum, cell) => sum + cell.overLimitAmount, 0);
  });
  
  totalHeldAmount = computed<number>(() => {
    const totalSales = this.totalBetAmount();
    if (this.activeMode() === 'အလယ်ဒိုင်') {
        return totalSales - this.forwardableOverLimitAmount();
    }
    return totalSales - this.totalOverLimitAmount();
  });
  
  payableCommissionAmount = computed<number>(() => this.totalHeldAmount() * (this.commissionToPay() / 100));
  
  receivableCommissionAmount = computed<number>(() => {
    if (this.activeMode() !== 'အလယ်ဒိုင်') return 0;
    return this.forwardableOverLimitAmount() * (this.commissionFromUpperBookie() / 100);
  });
  
  agentCommissionEarned = computed<number>(() => this.totalBetAmount() * (this.agentCommissionFromBookie() / 100));
  
  netAmount = computed<number>(() => {
    switch (this.activeMode()) {
      case 'အလယ်ဒိုင်':
        return this.totalHeldAmount() - this.payableCommissionAmount() + this.receivableCommissionAmount();
      case 'ဒိုင်ကြီး':
        return this.totalHeldAmount() - this.payableCommissionAmount();
      case 'အေးဂျင့်':
        return this.agentCommissionEarned();
      default: return 0;
    }
  });

  // --- Risk Analysis Computation ---
  riskAnalysis = computed<RiskAnalysis[]>(() => {
      const data = this.lotteryType() === '2D' ? this.gridCells() : this.listItems();
      const rate = this.payoutRate();
      const commPay = this.commissionToPay();
      
      const risks: RiskAnalysis[] = [];
      
      for(const cell of data) {
          if (cell.amount === 0) continue;
          
          const held = cell.amount - cell.overLimitAmount;
          if (held <= 0) continue;

          // Income from this number (Held - Commission)
          const income = held * (1 - (commPay / 100));
          // Expense if this number wins
          const expense = held * rate;
          
          const net = income - expense;
          
          risks.push({
              number: cell.number,
              totalHeld: held,
              estimatedPayout: expense,
              netProfitLoss: net
          });
      }
      
      // Sort by Net Profit/Loss (Lowest/Negative first)
      return risks.sort((a, b) => a.netProfitLoss - b.netProfitLoss);
  });

  worst10Risks = computed(() => this.riskAnalysis().slice(10));

  agentsWithPerformance = computed<AgentWithPerformance[]>(() => {
    const salesMap = new Map<string, number>();
    this.lotteryData().forEach(bets => {
      bets.forEach(bet => {
        salesMap.set(bet.source, (salesMap.get(bet.source) || 0) + bet.amount);
      });
    });
    const currentAgents = this.agents();
    const agents = currentAgents.map(agent => ({ ...agent, totalSales: salesMap.get(agent.name) || 0 }));
    agents.sort((a, b) => this.agentSortBy() === 'sales' ? b.totalSales - a.totalSales : a.name.localeCompare(b.name));
    return agents;
  });
  
  isInboxSubmitDisabled = computed(() => {
    const input = this.inboxInput();
    if (!input.trim()) return true;
    if (this.selectedAgentForInbox()) return false;
  
    const agentLineMatch = input.match(/^Agent\s*:\s*(.+)/im);
    if (agentLineMatch) return false;
    
    const newFormatMatch = input.match(/^---\s*(.+?)\s*---/m);
    if (newFormatMatch) return false;
  
    const lines = input.split(/\r?\n/);
    const firstLineTrimmed = lines.find(l => l.trim() !== '')?.trim();
    if (firstLineTrimmed && !firstLineTrimmed.toLowerCase().startsWith('agent') && firstLineTrimmed.includes(':')) {
        return false;
    }
    
    if (firstLineTrimmed && !firstLineTrimmed.includes('=') && !/^\d+\s+\d+/.test(firstLineTrimmed)) {
      return false;
    }
    
    return true;
  });

  overLimitConfirmationText = computed(() => {
    const confirmation = this.pendingInboxConfirmation();
    if (!confirmation) {
      return '';
    }
    return confirmation.overLimitBets.map(b => `${b.number}=${b.amount}`).join(', ');
  });

  top10OverLimitCells = computed<GridCell[]>(() => {
    return this.overLimitCells()
      .sort((a, b) => b.overLimitAmount - a.overLimitAmount)
      .slice(0, 10);
  });
  
  inboxReplyText = computed(() => {
      const result = this.lastInboxResult();
      if (!result) return '';
      
      const header = `--- ${this.bookieName()} ---`;
      const today = new Date().toLocaleDateString('en-CA');
      let dateLine = `နေ့စွဲ: ${this.lotteryType() === '3D' ? this.formatDate(this.drawDate()) : today}`;
      if (this.lotteryType() === '2D') {
          const sessionText = this.session() === 'morning' ? 'မနက်ပိုင်း' : 'ညနေပိုင်း';
          dateLine += ` (${sessionText})`;
      }
      
      const agentLine = `Agent: ${result.agent}`;
      const separator = '--------------------';
      
      let statusBody = '';
      if (result.isAllAccepted) {
          statusBody = "စာရင်းအားလုံး လက်ခံရရှိပါသည်။";
      } else {
          statusBody = "လစ်မစ်ကျော် ဂဏန်းများမှလွဲ၍ ကျန်စာရင်းများ လက်ခံရရှိပါသည်။\n\n(မရသော ဂဏန်းများ)\n" + (result.rejectedText || '-');
      }
      
      const totalLine = `စုစုပေါင်း လက်ခံငွေ: ${result.totalAccepted.toLocaleString()} ${this.currencySymbol()}`;
      const footer = "ကျေးဇူးတင်ပါသည်။";
      
      return `${header}\n${dateLine}\n${agentLine}\n${separator}\n${statusBody}\n${separator}\n${totalLine}\n${footer}`;
  });

  constructor() {
    window.addEventListener('online', () => this.isOnline.set(true));
    window.addEventListener('offline', () => this.isOnline.set(false));
      
    // Persistence Effects
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_agents_middle', this.middleBookieAgents());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_agents_main', this.mainBookieAgents());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_upper_bookies', this.upperBookies());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_agent_upper_bookies', this.agentUpperBookies());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_currency', this.currencySymbol());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_active_mode', this.activeMode());
      }
    });
    effect(() => {
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_selected_type', this.lotteryType());
      }
    });
    effect(() => {
      const state = this.appState()['2D'];
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_app_state_2d', state);
      }
    });
    effect(() => {
      const state = this.appState()['3D'];
      if(this.isDataLoaded()) {
        this.persistenceService.set('lottery_app_state_3d', state);
      }
    });
    
    effect(() => {
      const currentAgents = this.agents();
      if (currentAgents.length > 0 && !currentAgents.some(a => a.name === this.selectedAgentForInbox())) {
        this.selectedAgentForInbox.set(currentAgents[0].name);
      } else if (currentAgents.length === 0) {
        this.selectedAgentForInbox.set(null);
      }
    });

    effect(() => {
      const topNumbers = this.top10OverLimitCells();
      const mode = this.activeMode();
      const type = this.lotteryType();
  
      if (topNumbers.length === 0 || mode === 'အေးဂျင့်' || type !== '2D') {
        this.profitOptimizerSuggestion.set(null);
        return;
      }
  
      const totalOverLimitOfTop10 = topNumbers.reduce((sum, cell) => sum + cell.overLimitAmount, 0);
      const averageOverLimit = totalOverLimitOfTop10 / topNumbers.length;
      
      const baseSuggestion = averageOverLimit * 0.25;
      let suggestedHoldingIncrease = 0;

      if (baseSuggestion > 10000) suggestedHoldingIncrease = Math.round(baseSuggestion / 1000) * 1000;
      else if (baseSuggestion > 1000) suggestedHoldingIncrease = Math.round(baseSuggestion / 100) * 100;
      else if (baseSuggestion > 100) suggestedHoldingIncrease = Math.round(baseSuggestion / 50) * 50;
      else { this.profitOptimizerSuggestion.set(null); return; }

      if (suggestedHoldingIncrease <= 0) { this.profitOptimizerSuggestion.set(null); return; }
      
      let potentialProfitIncrease = 0;
      const commToPay = this.commissionToPay();
      const commFromUpper = this.commissionFromUpperBookie();

      for (const cell of topNumbers) {
        const extraHeldAmount = Math.min(cell.overLimitAmount, suggestedHoldingIncrease);
        if (mode === 'အလယ်ဒိုင်') potentialProfitIncrease += extraHeldAmount * (1 - (commToPay / 100) - (commFromUpper / 100));
        else potentialProfitIncrease += extraHeldAmount * (1 - (commToPay / 100));
      }
      
      if (potentialProfitIncrease <= 0) { this.profitOptimizerSuggestion.set(null); return; }
  
      this.profitOptimizerSuggestion.set({ topNumbers, suggestedHoldingIncrease, potentialProfitIncrease });
      this.suggestionAppliedRecently.set(false);
    });
  }

  async ngOnInit(): Promise<void> {
    const [legacyAgents, midAgents, mainAgents, upperBookies, agentUpperBookies, currency] = await Promise.all([
      this.persistenceService.get<Agent[]>('lottery_agents'),
      this.persistenceService.get<Agent[]>('lottery_agents_middle'),
      this.persistenceService.get<Agent[]>('lottery_agents_main'),
      this.persistenceService.get<UpperBookie[]>('lottery_upper_bookies'),
      this.persistenceService.get<{name: string}[]>('lottery_agent_upper_bookies'),
      this.persistenceService.get<'K' | '฿' | '¥'>('lottery_currency'),
    ]);

    if (midAgents) this.middleBookieAgents.set(midAgents);
    if (mainAgents) {
        this.mainBookieAgents.set(mainAgents);
    } else if (legacyAgents) {
        this.mainBookieAgents.set(legacyAgents);
    }

    if (upperBookies) this.upperBookies.set(upperBookies);
    if (agentUpperBookies) this.agentUpperBookies.set(agentUpperBookies);
    if (currency) this.currencySymbol.set(currency);

    const lastActiveMode = await this.persistenceService.get<string>('lottery_active_mode');
    if (lastActiveMode && this.modes.includes(lastActiveMode)) {
        this.activeMode.set(lastActiveMode);
    }

    const lastLotteryType = await this.persistenceService.get<LotteryType>('lottery_selected_type');
    if (lastLotteryType && ['2D', '3D'].includes(lastLotteryType)) {
        this.lotteryType.set(lastLotteryType);
    }

    const storedState2D = await this.persistenceService.get<AppState>('lottery_app_state_2d');
    const storedState3D = await this.persistenceService.get<AppState>('lottery_app_state_3d');
    
    this.appState.update(current => ({
      '2D': this.mergeState(current['2D'], storedState2D),
      '3D': this.mergeState(current['3D'], storedState3D)
    }));
    
    this.isDataLoaded.set(true);
  }

  private createInitialState(type: LotteryType): AppState {
    const today = new Date().toISOString().split('T')[0];
    const defaultName = type === '2D' ? 'My 2D' : 'My 3D';
    return {
      betHistory: [],
      defaultLimit: type === '2D' ? 50000 : 500000,
      payoutRate: type === '2D' ? 80 : 500,
      commissionToPay: 10,
      commissionFromUpperBookie: 10,
      agentCommissionFromBookie: 10,
      individualLimits: new Map<string, number>(),
      myAgentName: defaultName + ' Agent',
      agentProfiles: [defaultName + ' Agent'],
      myMiddleBookieName: defaultName + ' Middle',
      myMainBookieName: defaultName + ' Main',
      session: 'morning',
      drawDate: today,
      userInput: '',
      voucherSettings: {
          headerText: defaultName,
          footerText: 'ကံကောင်းပါစေ',
          fontSize: 'medium',
          showDateTime: true
      } as VoucherSettings
    };
  }

  private mergeState(initial: AppState, stored?: AppState | null): AppState {
    if (!stored) return initial;
    
    const legacyName = (stored as any).bookieName;
    const storedAgentName = (stored as any).myAgentName;
    const myAgentName = (storedAgentName !== undefined && storedAgentName !== null) ? storedAgentName : (legacyName || initial.myAgentName);
    const storedMiddleName = (stored as any).myMiddleBookieName;
    const myMiddleBookieName = (storedMiddleName !== undefined && storedMiddleName !== null) ? storedMiddleName : (legacyName || initial.myMiddleBookieName);
    const storedMainName = (stored as any).myMainBookieName;
    const myMainBookieName = (storedMainName !== undefined && storedMainName !== null) ? storedMainName : (legacyName || initial.myMainBookieName);
    
    let profiles = (stored as any).agentProfiles;
    if (!profiles || !Array.isArray(profiles) || profiles.length === 0) {
        profiles = [myAgentName];
    } else if (!profiles.includes(myAgentName)) {
        profiles = [...profiles, myAgentName];
    }
    
    return {
      ...initial,
      ...stored,
      individualLimits: new Map(stored.individualLimits),
      myAgentName,
      myMiddleBookieName,
      myMainBookieName,
      agentProfiles: profiles,
      voucherSettings: stored.voucherSettings || initial.voucherSettings // Default fallback if missing
    };
  }
  
  updateCurrentState(key: keyof AppState, value: any): void {
      const type = this.lotteryType();
      this.appState.update(current => ({
        ...current,
        [type]: {
          ...current[type],
          [key]: value
        }
      }));
  }

  updateBookieName(name: string) {
      const mode = this.activeMode();
      let key: keyof AppState;
      if (mode === 'အေးဂျင့်') key = 'myAgentName';
      else if (mode === 'အလယ်ဒိုင်') key = 'myMiddleBookieName';
      else key = 'myMainBookieName';
      
      this.updateCurrentState(key, name);
  }

  onProfileSelect(event: Event) {
      const select = event.target as HTMLSelectElement;
      const name = select.value;
      if (name) {
          this.updateBookieName(name);
          select.value = '';
      }
  }

  addAgentProfile() {
      const currentName = this.bookieName().trim();
      if (currentName) {
          const type = this.lotteryType();
          this.appState.update(current => {
              const profiles = current[type].agentProfiles || [];
              if (profiles.includes(currentName)) {
                  this.statusMessage.set("ဤအမည်ရှိပြီးသားဖြစ်ပါသည်။");
                  setTimeout(() => this.statusMessage.set(""), 2000);
                  return current;
              }
              this.statusMessage.set(`'${currentName}' ကို Profile စာရင်းတွင် သိမ်းဆည်းလိုက်ပါသည်။`);
              setTimeout(() => this.statusMessage.set(""), 2000);
              return { ...current, [type]: { ...current[type], agentProfiles: [...profiles, currentName] } };
          });
      } else {
          this.statusMessage.set("အမည်ရိုက်ထည့်ပါ");
          setTimeout(() => this.statusMessage.set(""), 2000);
      }
  }

  removeAgentProfile() {
      const currentName = this.bookieName();
      const profiles = this.agentProfiles();
      if (profiles.length <= 1) {
          alert("အနည်းဆုံး အမည်တစ်ခု ကျန်ရှိနေရပါမည်။");
          return;
      }
      if (confirm(`'${currentName}' ကို Profile စာရင်းမှ ဖျက်ရန် သေချာပါသလား?`)) {
           const type = this.lotteryType();
           this.appState.update(current => {
              const newProfiles = profiles.filter(p => p !== currentName);
              let nextName = current[type].myAgentName;
              if (nextName === currentName) nextName = newProfiles[0];
              return { ...current, [type]: { ...current[type], agentProfiles: newProfiles, myAgentName: nextName } };
           });
           this.statusMessage.set("ဖျက်ပြီးပါပြီ။");
           setTimeout(() => this.statusMessage.set(""), 2000);
      }
  }

  handleKeyboardEvents(event: KeyboardEvent) {
    if (this.isPanicMode()) {
       const key = event.key;
       
       // Allow Toggle Off with F9 again (Quick Exit)
       if (key === 'F9') {
           this.isPanicMode.set(false);
           return;
       }

       // Block underlying interactions
       event.preventDefault();

       // Map Keyboard to Calculator Input
       if (/^[0-9]$/.test(key)) {
           this.onPanicCalculatorInput(key);
       } else if (['+', '-', '*', '/'].includes(key)) {
           this.onPanicCalculatorInput(key);
       } else if (key === 'Enter' || key === '=') {
           this.onPanicCalculatorInput('=');
       } else if (key === 'Backspace') {
           this.panicInput.update(v => v.slice(0, -1));
       } else if (key === 'Delete' || key.toLowerCase() === 'c') {
           this.onPanicCalculatorInput('C');
       } else if (key === 'Escape') {
           this.panicInput.set('');
       }
       return; 
    }

    if (event.key === 'F9' || event.key === 'Escape') {
       if (event.key === 'Escape') {
           const now = Date.now();
           if (now - this.lastEscTime < 300) {
               this.activatePanicMode();
           }
           this.lastEscTime = now;
       } else {
           this.activatePanicMode(); // F9 instant
       }
    }

    if (this.showReports() || this.showUserGuide() || this.showSubmissionModal() || this.showPayoutModal() || this.showBetDetailModal() || this.isForwardingModalOpen() || this.showLimitManagementModal() || this.showVoucherSettings() || this.showRiskModal()) return;
    
    const target = event.target as HTMLElement;
    if (['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) && target.id !== 'main-bet-input') return;

    if (event.altKey) {
      event.preventDefault();
      switch (event.key.toLowerCase()) {
        case 'c': this.clearAllBets(); break;
        case 'z': this.undoLastBet(); break;
        case 's': this.saveReport(); break;
        case 'm': if (this.lotteryType() === '2D') this.setSession(this.session() === 'morning' ? 'evening' : 'morning'); break;
        case '1': this.setActiveMode(this.modes[0]); break;
        case '2': this.setActiveMode(this.modes[1]); break;
        case '3': this.setActiveMode(this.modes[2]); break;
        case 'b': this.backupData(); break;
        case 'r': this.fileInput.nativeElement.click(); break;
        case 'p': if (this.activeMode() !== 'အေးဂျင့်') this.openPayoutModal(); break;
        case 'd': this.setLotteryType(this.lotteryType() === '2D' ? '3D' : '2D'); break;
      }
    }
  }
  private lastEscTime = 0;

  // --- Panic Mode Logic ---
  activatePanicMode() {
      this.isPanicMode.set(true);
      this.panicInput.set('');
  }
  
  onPanicCalculatorInput(val: string) {
      if (val === 'C') {
          this.panicInput.set('');
      } else if (val === '=') {
          const currentInput = this.panicInput();
          // Unlock Code check
          if (currentInput === '1234') {
              this.isPanicMode.set(false);
              this.panicInput.set('');
          } else {
              // Actual Calculator Logic
              try {
                  // Basic validation to prevent unsafe eval
                  if (/^[0-9+\-*/.]+$/.test(currentInput)) {
                      // Use Function constructor for safer evaluation than direct eval
                      // eslint-disable-next-line no-new-func
                      const result = new Function('return ' + currentInput)();
                      this.panicInput.set(String(result));
                  } else {
                      throw new Error('Invalid input');
                  }
              } catch (e) {
                  this.panicInput.set('Error');
                  setTimeout(() => this.panicInput.set(''), 1000);
              }
          }
      } else {
          this.panicInput.update(v => v + val);
      }
  }

  // --- Voice Logic ---
  toggleVoiceInput() {
      if (this.voiceService.isListening()) {
          this.voiceService.stopListening();
      } else {
          this.voiceService.startListening((text, isFinal) => {
              // Command Mode Logic
              if (text.includes('ပြန်ဖျက်') || text.toLowerCase().includes('cancel')) {
                  this.updateCurrentState('userInput', '');
                  this.statusMessage.set('အသံဖြင့် ပြန်ဖျက်လိုက်ပါပြီ။');
                  setTimeout(() => this.statusMessage.set(''), 2000);
                  return;
              }
              if (text.includes('ထည့်မယ်') || text.toLowerCase().includes('save')) {
                  this.addBetsFromInput();
                  this.statusMessage.set('အသံဖြင့် သိမ်းဆည်းလိုက်ပါပြီ။');
                  setTimeout(() => this.statusMessage.set(''), 2000);
                  return;
              }

              // Update Input
              this.updateCurrentState('userInput', text);
          });
      }
  }

  onBeforeUnload(event: BeforeUnloadEvent) {
    if (this.betHistory().length > 0) {
      event.preventDefault();
      event.returnValue = true;
    }
  }

  onInputKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.addBetsFromInput();
    }
  }

  setLotteryType(type: LotteryType) { this.lotteryType.set(type); }
  setActiveMode(mode: string): void { this.activeMode.set(mode); }
  setSession(session: 'morning' | 'evening'): void {
    this.appState.update(current => ({
      ...current,
      '2D': {
        ...current['2D'],
        session: session
      }
    }));
  }
  toggleReports(): void { this.showReports.update(v => !v); }
  toggleHeatmap(): void { this.showHeatmap.update(v => !v); }

  addBetsFromInput(): void {
    const input = this.userInput().trim();
    if (!input) return;

    const source = this.activeMode() === 'အေးဂျင့်' ? this.bookieName() : 'Direct Input';
    if (this.addBetsToHistory(input, source)) {
      if (this.activeMode() === 'အေးဂျင့်') {
        this.pendingSubmissions.update(s => [...s, input]);
      }
      this.updateCurrentState('userInput', '');
    }
  }

  private addBetsToHistory(input: string, source: string): boolean {
    const parsedBets = this.betParsingService.parseRaw(input, this.lotteryType());
    if (parsedBets.length === 0) return false;

    const newEntry: HistoryEntry = { 
        id: crypto.randomUUID(), 
        input, 
        source,
        mode: this.activeMode() 
    };
    
    const type = this.lotteryType();
    this.appState.update(current => ({
      ...current,
      [type]: {
        ...current[type],
        betHistory: [...current[type].betHistory, newEntry]
      }
    }));
    return true;
  }
  
  clearAllBets(): void {
    if (this.recentHistory().length === 0) {
      this.statusMessage.set('ဖျက်ရန် စာရင်းများမရှိသေးပါ။');
      setTimeout(() => this.statusMessage.set(''), 3000);
      return;
    }
    this.showClearAllConfirmation.set(true);
  }

  confirmClearAll(): void {
    const type = this.lotteryType();
    const currentMode = this.activeMode();

    this.appState.update(current => {
      const currentHistory = current[type].betHistory;
      const retainedHistory = currentHistory.filter(h => {
          const entryMode = h.mode || 'ဒိုင်ကြီး';
          return entryMode !== currentMode;
      });

      return {
        ...current,
        [type]: {
          ...current[type],
          betHistory: retainedHistory,
          userInput: '',
        }
      };
    });

    this.inboxInput.set('');
    this.confirmationMessage.set('');
    this.submissionText.set('');
    
    if (currentMode === 'အေးဂျင့်') {
        this.pendingSubmissions.set([]);
    }
    
    if (currentMode === 'အလယ်ဒိုင်' || currentMode === 'ဒိုင်ကြီး') {
        this.acceptedSubmissions.set([]);
        this.acknowledgedOverLimits.set(new Map());
        this.rejectedOverLimits.set(new Set());
        this.acknowledgedHeldOverLimits.set(new Map());
    }

    this.showClearAllConfirmation.set(false);
    this.profitOptimizerSuggestion.set(null);
    this.lastInboxResult.set(null);
    this.statusMessage.set('စာရင်းအားလုံးကို အောင်မြင်စွာ ဖျက်လိုက်ပါပြီ။');
    setTimeout(() => this.statusMessage.set(''), 3000);
  }

  undoLastBet(): void {
    const type = this.lotteryType();
    const currentMode = this.activeMode();
    const history = this.appState()[type].betHistory;
    
    let indexToRemove = -1;
    for (let i = history.length - 1; i >= 0; i--) {
        const h = history[i];
        const entryMode = h.mode || 'ဒိုင်ကြီး';
        if (entryMode === currentMode) {
            indexToRemove = i;
            break;
        }
    }

    if (indexToRemove === -1) return;
    
    const entryToDelete = history[indexToRemove];
    const newHistory = [...history];
    newHistory.splice(indexToRemove, 1);

    this.appState.update(current => ({
      ...current,
      [type]: {
        ...current[type],
        betHistory: newHistory
      }
    }));
    
    if (this.activeMode() === 'အေးဂျင့်' && entryToDelete.source === this.bookieName()) {
      this.pendingSubmissions.update(submissions => {
        const index = submissions.lastIndexOf(entryToDelete.input);
        if (index > -1) {
          const newSubmissions = [...submissions];
          newSubmissions.splice(index, 1);
          return newSubmissions;
        }
        return submissions;
      });
    }
  }

  deleteHistoryEntry(idToDelete: string): void {
    const type = this.lotteryType();
    const entryToDelete = this.betHistory().find(h => h.id === idToDelete);
    if (!entryToDelete) return;

    this.appState.update(current => ({
      ...current,
      [type]: {
        ...current[type],
        betHistory: current[type].betHistory.filter(e => e.id !== idToDelete)
      }
    }));
    
    if (this.activeMode() === 'အေးဂျင့်' && entryToDelete.source === this.bookieName()) {
      this.pendingSubmissions.update(submissions => {
        const index = submissions.indexOf(entryToDelete.input);
        if (index > -1) {
          const newSubmissions = [...submissions];
          newSubmissions.splice(index, 1);
          return newSubmissions;
        }
        return submissions;
      });
    }
  }

  editHistoryEntry(entryToEdit: HistoryEntry): void {
    this.updateCurrentState('userInput', entryToEdit.input);
    this.deleteHistoryEntry(entryToEdit.id);
    this.mainBetInput.nativeElement.focus();
  }

  addAgent() {
    const name = this.newAgentName().trim();
    const commission = this.newAgentCommission();
    const mode = this.activeMode();

    if (name && commission >= 0) {
        if (mode === 'အလယ်ဒိုင်') {
            if (!this.middleBookieAgents().some(a => a.name === name)) {
                this.middleBookieAgents.update(a => [...a, { name, commission }]);
                this.newAgentName.set('');
            }
        } else if (mode === 'ဒိုင်ကြီး') {
            if (!this.mainBookieAgents().some(a => a.name === name)) {
                this.mainBookieAgents.update(a => [...a, { name, commission }]);
                this.newAgentName.set('');
            }
        }
    }
  }

  removeAgent(agentNameToRemove: string) { 
      const mode = this.activeMode();
      if (mode === 'အလယ်ဒိုင်') {
          this.middleBookieAgents.update(a => a.filter(agent => agent.name !== agentNameToRemove));
      } else if (mode === 'ဒိုင်ကြီး') {
          this.mainBookieAgents.update(a => a.filter(agent => agent.name !== agentNameToRemove));
      }
  }
  
  addUpperBookie() {
    const name = this.newUpperBookieName().trim();
    const commission = this.newUpperBookieCommission();
    if (name && commission >= 0 && !this.upperBookies().some(b => b.name === name)) {
      this.upperBookies.update(b => [...b, { name, commission }]);
      this.newUpperBookieName.set('');
    }
  }
  removeUpperBookie(bookieNameToRemove: string) { this.upperBookies.update(b => b.filter(bookie => bookie.name !== bookieNameToRemove)); }
  
  addAgentUpperBookie() {
    const name = this.newAgentUpperBookieName().trim();
    if (name && !this.agentUpperBookies().some(b => b.name === name)) {
      this.agentUpperBookies.update(b => [...b, { name }]);
      this.newAgentUpperBookieName.set('');
    }
  }
  removeAgentUpperBookie(bookieNameToRemove: string) { this.agentUpperBookies.update(b => b.filter(bookie => bookie.name !== bookieNameToRemove)); }

  // --- Limit Management ---
  openLimitModal(number: string | null = null) {
    if (this.activeMode() === 'အေးဂျင့်') return;
    this.limitManageNumber.set(number || '');
    const currentLimit = number ? (this.individualLimits().get(number) || this.defaultLimit()) : this.defaultLimit();
    this.limitManageAmount.set(currentLimit);
    this.showLimitManagementModal.set(true);
  }

  saveIndividualLimit() {
    const number = this.limitManageNumber().trim();
    const limit = this.limitManageAmount();
    
    if (number && !isNaN(limit) && limit >= 0) {
      const type = this.lotteryType();
      this.appState.update(current => {
        const newLimits = new Map(current[type].individualLimits);
        newLimits.set(number, limit);
        return {
          ...current,
          [type]: {
            ...current[type],
            individualLimits: newLimits
          }
        };
      });
      if (!this.limitManageNumber()) {
          this.limitManageNumber.set('');
          this.limitManageAmount.set(this.defaultLimit());
          this.statusMessage.set('လစ်မစ်သတ်မှတ်ပြီးပါပြီ။');
          setTimeout(() => this.statusMessage.set(''), 2000);
      } else {
        this.showLimitManagementModal.set(false);
      }
    } else {
        this.statusMessage.set('ကျေးဇူးပြု၍ ဂဏန်းနှင့် ပမာဏကို မှန်ကန်စွာထည့်ပါ။');
        setTimeout(() => this.statusMessage.set(''), 3000);
    }
  }

  removeIndividualLimit(number: string) {
      const type = this.lotteryType();
      this.appState.update(current => {
        const newLimits = new Map(current[type].individualLimits);
        newLimits.delete(number);
        return {
          ...current,
          [type]: {
            ...current[type],
            individualLimits: newLimits
          }
        };
      });
      if (this.limitManageNumber() === number) {
          this.showLimitManagementModal.set(false);
      }
  }

  closeLimitModal() {
    this.showLimitManagementModal.set(false);
    this.limitManageNumber.set('');
  }

  addBetsFromInbox(): void {
    let input = this.inboxInput().trim();
    if (!input) return;
    
    let agentName: string | null = this.selectedAgentForInbox();
    let betContent = input;

    const lines = input.split(/\r?\n/);
    const firstLine = lines[0].trim();
    
    const dashMatch = firstLine.match(/^---\s*(.+?)\s*---$/);
    const colonMatch = firstLine.match(/^(?:Agent\s*:\s*)?([^:]+)$/i);
    
    let potentialName = '';
    if (dashMatch) {
      potentialName = dashMatch[1].trim();
    } else if (colonMatch) {
        if (!firstLine.includes('=') && !/^\d+\s+\d+/.test(firstLine)) {
            potentialName = firstLine.replace(/^Agent\s*:\s*/i, '').trim();
        }
    }

    if (potentialName) {
      if (this.agents().some(a => a.name === potentialName)) {
          agentName = potentialName;
          this.selectedAgentForInbox.set(potentialName);
      } 
      else if (!agentName && potentialName.length < 20) {
          agentName = potentialName;
          this.selectedAgentForInbox.set(potentialName);
      }
    }
    
    if (!agentName) {
        this.statusMessage.set('ကျေးဇူးပြု၍ Agent ကို ရွေးချယ်ပါ သို့မဟုတ် စာရင်းတွင် Agent အမည် ထည့်သွင်းပါ။');
        setTimeout(() => this.statusMessage.set(''), 3000);
        return;
    }
    
    const finalAgentName = agentName as string;

    if (finalAgentName) {
        const escapedName = finalAgentName.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        const headerRegex = new RegExp(`^\\s*(?:---|Agent\\s*:)?\\s*${escapedName}\\s*(?:---)?\\s*(?:\\r?\\n|$)`, 'i');
        
        if (headerRegex.test(betContent)) {
            betContent = betContent.replace(headerRegex, '').trim();
        }
    }

    const currentMode = this.activeMode();
    const currentAgentList = this.agents();
    
    if (!currentAgentList.some(a => a.name === finalAgentName)) {
      if (currentMode === 'အလယ်ဒိုင်') {
          this.middleBookieAgents.update(a => [...a, { name: finalAgentName, commission: 5 }]);
      } else if (currentMode === 'ဒိုင်ကြီး') {
          this.mainBookieAgents.update(a => [...a, { name: finalAgentName, commission: 5 }]);
      }
      this.statusMessage.set(`အေးဂျင့် '${finalAgentName}' ကို အလိုအလျောက် စာရင်းသွင်းလိုက်သည်။`);
    }
    
    const rawBets = this.betParsingService.parseRaw(betContent, this.lotteryType());
    
    if (rawBets.length === 0) {
        if (betContent.length > 20) {
            this.statusMessage.set('Format တွေ့သော်လည်း စာရင်းများမတွေ့ပါ။ 2D/3D Mode မှန်ကန်ကြောင်း စစ်ဆေးပါ။');
        } else {
            this.statusMessage.set('ထည့်သွင်းရန် မှန်ကန်သောစာရင်းများ မတွေ့ရှိပါ။');
        }
        setTimeout(() => this.statusMessage.set(''), 4000);
        return;
    }
    
    const safeBets: Bet[] = [];
    const overLimitBets: Bet[] = [];
    const currentData = this.lotteryData();
    const currentIndLimits = this.individualLimits();
    const currentDefLimit = this.defaultLimit();

    const tempCurrentDataMap = new Map<string, number>();
    currentData.forEach((bets, number) => {
        const total = bets.reduce((sum, b) => sum + b.amount, 0);
        tempCurrentDataMap.set(number, total);
    });

    rawBets.forEach(bet => {
        const number = bet.number;
        const amount = bet.amount;
        
        const existingAmount = tempCurrentDataMap.get(number) || 0;
        const limit = currentIndLimits.get(number) ?? currentDefLimit;
        
        if (existingAmount >= limit) {
            overLimitBets.push({ number, amount });
        } else if (existingAmount + amount > limit) {
            const safeAmount = limit - existingAmount;
            const rejectedAmount = amount - safeAmount;
            
            if (safeAmount > 0) {
                safeBets.push({ number, amount: safeAmount });
            }
            if (rejectedAmount > 0) {
                overLimitBets.push({ number, amount: rejectedAmount });
            }
            tempCurrentDataMap.set(number, limit);
        } else {
            safeBets.push({ number, amount });
            tempCurrentDataMap.set(number, existingAmount + amount);
        }
    });

    if (overLimitBets.length > 0) {
        this.pendingInboxConfirmation.set({
            safeBets,
            overLimitBets,
            agent: finalAgentName,
            originalInput: betContent
        });
    } else {
        if (this.addBetsToHistory(betContent, finalAgentName)) {
            const totalAmount = rawBets.reduce((sum, b) => sum + b.amount, 0);
            this.acceptedSubmissions.update(s => [...s, { agent: finalAgentName, content: betContent, timestamp: new Date(), total: totalAmount }]);
            this.inboxInput.set('');
            
            this.lastInboxResult.set({
                agent: finalAgentName,
                totalAccepted: totalAmount,
                isAllAccepted: true
            });
            
            this.statusMessage.set(`'${finalAgentName}' ၏ စာရင်းကို အောင်မြင်စွာ လက်ခံပြီးပါပြီ။`);
            setTimeout(() => this.statusMessage.set(''), 3000);
        }
    }
  }

  acceptAllFromInbox(): void {
    const confirmation = this.pendingInboxConfirmation();
    if (!confirmation) return;

    if (this.addBetsToHistory(confirmation.originalInput, confirmation.agent)) {
      const totalAmount = [...confirmation.safeBets, ...confirmation.overLimitBets].reduce((sum: number, b: Bet) => sum + b.amount, 0);
      this.acceptedSubmissions.update(s => [...s, { agent: confirmation.agent, content: confirmation.originalInput, timestamp: new Date(), total: totalAmount }]);
      this.inboxInput.set('');
      
      this.lastInboxResult.set({
         agent: confirmation.agent,
         totalAccepted: totalAmount,
         isAllAccepted: true
      });

      this.statusMessage.set(`'${confirmation.agent}' ၏ စာရင်းအားလုံးကို အောင်မြင်စွာ လက်ခံပြီးပါပြီ။`);
      setTimeout(() => this.statusMessage.set(''), 3000);
    }
    this.cancelInboxConfirmation();
  }

  acceptSafeOnlyFromInbox(): void {
    const confirmation = this.pendingInboxConfirmation();
    if (!confirmation) return;

    const safeBetsString = confirmation.safeBets.map(b => `${b.number} ${b.amount}`).join('\n');
    let safeTotal = 0;

    if (safeBetsString) {
        if (this.addBetsToHistory(safeBetsString, confirmation.agent)) {
            safeTotal = confirmation.safeBets.reduce((sum: number, b: Bet) => sum + b.amount, 0);
            this.acceptedSubmissions.update(s => [...s, { agent: confirmation.agent, content: safeBetsString, timestamp: new Date(), total: safeTotal }]);
        }
    }

    const overLimitText = confirmation.overLimitBets.map(b => `${b.number}=${b.amount}`).join(', ');
    
    this.lastInboxResult.set({
        agent: confirmation.agent,
        totalAccepted: safeTotal,
        rejectedText: overLimitText,
        isAllAccepted: false
    });

    if (safeTotal > 0) {
        this.statusMessage.set('လစ်မစ်အတွင်း စာရင်းများကိုသာ လက်ခံပြီးပါပြီ။');
    } else {
        this.statusMessage.set('စာရင်းအားလုံး လစ်မစ်ကျော်နေသဖြင့် ပယ်ဖျက်လိုက်ပါသည်။ (Reply Voucher တွင် ကြည့်ပါ)');
    }
    
    setTimeout(() => this.statusMessage.set(''), 4000);

    this.inboxInput.set('');
    this.cancelInboxConfirmation();
  }

  cancelInboxConfirmation(): void {
    this.pendingInboxConfirmation.set(null);
    this.confirmationMessage.set('');
  }
  
  closeInboxResult(): void {
      this.lastInboxResult.set(null);
  }
  
  copyInboxReply(): void {
      this.copyToClipboard(this.inboxReplyText());
      this.statusMessage.set('Reply Voucher ကို ကူးယူပြီးပါပြီ။');
      setTimeout(() => this.statusMessage.set(''), 2000);
  }

  openSubmissionModal() {
    if (this.pendingSubmissions().length === 0) return;
    
    const allBets: { number: string; amount: number }[] = [];
    const pending = this.pendingSubmissions();
    
    for (const input of pending) {
        const bets = this.betParsingService.parseRaw(input, this.lotteryType());
        allBets.push(...bets);
    }

    const today = new Date().toLocaleDateString('en-CA');
    let dateLine = `နေ့စွဲ: ${this.lotteryType() === '3D' ? this.formatDate(this.drawDate()) : today}`;
    if (this.lotteryType() === '2D') {
        const sessionText = this.session() === 'morning' ? 'မနက်ပိုင်း' : 'ညနေပိုင်း';
        dateLine += ` (${sessionText})`;
    }

    const header = `--- ${this.bookieName()} ---`;
    const separator = '--------------------';
    
    const body = allBets.map(b => `${b.number} = ${b.amount}`).join('\n');
    const totalAmount = allBets.reduce((sum, b) => sum + b.amount, 0);
    const count = allBets.length;

    const footer = `စုစုပေါင်း (${count}) ကွက်: ${totalAmount.toLocaleString()} ${this.currencySymbol()}`;

    const formattedText = `${header}\n${dateLine}\n${separator}\n${body}\n${separator}\n${footer}`;

    this.submissionText.set(formattedText);
    this.showSubmissionModal.set(true);
  }

  copySubmissionText() {
    this.copyToClipboard(this.submissionText());
    this.statusMessage.set('စာရင်းကို Copy ကူးပြီးပါပြီ။');
    setTimeout(() => this.statusMessage.set(''), 3000);
  }

  finishBatch() {
    this.copyToClipboard(this.submissionText());
    this.pendingSubmissions.set([]); 
    this.showSubmissionModal.set(false);
    this.statusMessage.set('စာရင်းပို့ပြီးပါပြီ။ နောက်တစ်သုတ် စတင်နိုင်ပါပြီ။ (ပင်မဇယားတွင် စုစုပေါင်း ကျန်ရှိနေမည်)');
    setTimeout(() => this.statusMessage.set(''), 4000);
  }
  
  clearSubmissions() {
    this.pendingSubmissions.set([]);
  }
  
  openPayoutModal() { this.showPayoutModal.set(true); this.payoutDetails.set(null); this.winningNumber.set(''); }
  
  calculatePayout() {
    const num = this.winningNumber().trim();
    const type = this.lotteryType();
    const requiredLength = type === '2D' ? 2 : 3;

    if (num.length !== requiredLength || isNaN(parseInt(num))) { alert(`ကျေးဇူးပြု၍ ဂဏန်း ${requiredLength} လုံးကို မှန်ကန်စွာထည့်ပါ။`); return; }
    
    const currentIndLimits = this.individualLimits();
    const currentDefLimit = this.defaultLimit();
    const limit = currentIndLimits.get(num) ?? currentDefLimit;

    const cell = (type === '2D' ? this.gridCells() : this.listItems()).find(c => c.number === num);
    const winningBetsBreakdown = cell ? cell.breakdown : [];
    
    const totalBet = cell ? cell.amount : 0;
    const totalOverLimitBet = cell ? cell.overLimitAmount : 0;
    const totalHeldBet = totalBet - totalOverLimitBet;
    
    const totalHeldPayout = totalHeldBet * this.payoutRate();
    const totalOverLimitPayout = totalOverLimitBet * this.payoutRate();
    
    const history = this.betHistory();
    const historyIndexMap = new Map<string, number>();
    history.forEach((h, i) => historyIndexMap.set(h.id, i));

    const sortedBets = [...winningBetsBreakdown].sort((a, b) => {
        const idxA = historyIndexMap.get(a.historyEntryId) ?? Infinity;
        const idxB = historyIndexMap.get(b.historyEntryId) ?? Infinity;
        return idxA - idxB;
    });

    const sourceHeldMap = new Map<string, number>();
    const sourceTotalMap = new Map<string, number>(); // For reference/debug if needed
    const sourceWinBetsMap = new Map<string, number[]>();

    let currentTotalHeld = 0;

    sortedBets.forEach(bet => {
        const remainingCapacity = Math.max(0, limit - currentTotalHeld);
        let heldPortion = 0;

        if (remainingCapacity > 0) {
            heldPortion = Math.min(bet.amount, remainingCapacity);
            currentTotalHeld += heldPortion;
        }
        
        if (heldPortion > 0) {
            sourceHeldMap.set(bet.source, (sourceHeldMap.get(bet.source) || 0) + heldPortion);
        }
        
        sourceTotalMap.set(bet.source, (sourceTotalMap.get(bet.source) || 0) + bet.amount);
        
        const list = sourceWinBetsMap.get(bet.source) || [];
        list.push(bet.amount);
        sourceWinBetsMap.set(bet.source, list);
    });

    const agentPerformance = this.agentsWithPerformance();
    const agentSalesMap = new Map<string, number>();
    agentPerformance.forEach(a => agentSalesMap.set(a.name, a.totalSales));

    const knownAgentNames = new Set(this.agents().map(a => a.name));
    
    const agentPayouts: AgentPayoutInfo[] = [];
    const otherPayouts: AgentPayoutInfo[] = [];

    this.agents().forEach(agent => {
        const totalSales = agentSalesMap.get(agent.name) || 0;
        // Check if agent has sales OR has any winning bets (even if rejected/over limit, they are in the breakdown)
        if (totalSales > 0 || sourceWinBetsMap.has(agent.name)) {
            const heldWinBetAmount = sourceHeldMap.get(agent.name) || 0;
            const payout = heldWinBetAmount * this.payoutRate();
            
            const totalWinBetAmount = sourceTotalMap.get(agent.name) || 0;
            const totalWinAmount = totalWinBetAmount * this.payoutRate();

            const overLimitWinBetAmount = totalWinBetAmount - heldWinBetAmount;
            const overLimitWinAmount = overLimitWinBetAmount * this.payoutRate();

            const commissionRate = agent.commission;
            const commissionAmount = totalSales * (commissionRate / 100);
            const netSales = totalSales - commissionAmount;
            const finalBalance = netSales - payout; 

            agentPayouts.push({
                name: agent.name,
                totalSales,
                commissionRate,
                commissionAmount,
                netSales,
                
                totalWinBetAmount,
                totalWinAmount,
                overLimitWinBetAmount,
                overLimitWinAmount,
                heldWinBetAmount,
                payout, 
                
                finalBalance,
                individualBets: sourceWinBetsMap.get(agent.name) || []
            });
        }
    });

    const nonAgentSalesMap = new Map<string, number>();
    this.lotteryData().forEach(bets => {
        bets.forEach(bet => {
            if (!knownAgentNames.has(bet.source)) {
                 nonAgentSalesMap.set(bet.source, (nonAgentSalesMap.get(bet.source) || 0) + bet.amount);
            }
        });
    });

    nonAgentSalesMap.forEach((totalSales, source) => {
        if (knownAgentNames.has(source)) return;

        const heldWinBetAmount = sourceHeldMap.get(source) || 0;
        const payout = heldWinBetAmount * this.payoutRate();
        
        const totalWinBetAmount = sourceTotalMap.get(source) || 0;
        const totalWinAmount = totalWinBetAmount * this.payoutRate();

        const overLimitWinBetAmount = totalWinBetAmount - heldWinBetAmount;
        const overLimitWinAmount = overLimitWinBetAmount * this.payoutRate();
        
        const commissionRate = 0; 
        const commissionAmount = 0;
        const netSales = totalSales;
        const finalBalance = netSales - payout;

        otherPayouts.push({
             name: source,
             totalSales,
             commissionRate,
             commissionAmount,
             netSales,
             
             totalWinBetAmount,
             totalWinAmount,
             overLimitWinBetAmount,
             overLimitWinAmount,
             heldWinBetAmount,
             payout,

             finalBalance,
             individualBets: sourceWinBetsMap.get(source) || []
        });
    });

    agentPayouts.sort((a, b) => b.totalSales - a.totalSales);
    otherPayouts.sort((a, b) => b.totalSales - a.totalSales);
    
    this.payoutDetails.set({ 
        winningNumber: num, 
        totalBet,
        totalHeldBet, 
        totalHeldPayout, 
        totalOverLimitBet,
        totalOverLimitPayout,
        agentPayouts,
        otherPayouts
    });
  }

  printPayout() { window.print(); }

  async saveReport(): Promise<void> {
    if (this.lotteryData().size === 0) {
      this.statusMessage.set('မှတ်တမ်းတင်ရန် စာရင်းများမရှိသေးပါ။');
      setTimeout(() => this.statusMessage.set(''), 3000);
      return;
    }
    const type = this.lotteryType();
    const currentMode = this.activeMode();
    
    try {
        const filteredHistory = this.betHistory().filter(h => {
             const entryMode = h.mode || 'ဒိုင်ကြီး';
             return entryMode === currentMode;
        });

        const report: Report = {
            id: `report_${new Date().toISOString()}_${this.activeMode()}_${type === '2D' ? this.session() : this.drawDate()}_${type}`,
            lotteryType: type,
            date: new Date().toISOString(),
            session: type === '2D' ? this.session() : undefined,
            drawDate: type === '3D' ? this.drawDate() : undefined,
            mode: this.activeMode(),
            totalBetAmount: this.totalBetAmount(),
            totalOverLimitAmount: this.totalOverLimitAmount(),
            totalHeldAmount: this.totalHeldAmount(),
            payableCommissionAmount: this.payableCommissionAmount(),
            receivableCommissionAmount: this.receivableCommissionAmount(),
            agentCommissionEarned: this.agentCommissionEarned(),
            netAmount: this.netAmount(),
            lotteryData: Array.from(this.lotteryData().entries()).map(([key, value]) => {
                const totalAmount = value.reduce((sum, bet) => sum + bet.amount, 0);
                return [key, totalAmount];
            }),
            betHistory: filteredHistory.map(h => h.input),
            bookieName: this.bookieName(),
            defaultLimit: this.defaultLimit(),
            payoutRate: this.payoutRate(),
            commissionToPay: this.commissionToPay(),
            agentCommissionFromBookie: this.agentCommissionFromBookie(),
            commissionFromUpperBookie: this.commissionFromUpperBookie(),
            individualLimits: Array.from(this.individualLimits().entries()),
            upperBookies: this.upperBookies(),
            agents: this.agents(),
            currencySymbol: this.currencySymbol(),
        };
        await this.persistenceService.saveReport(report);
        this.statusMessage.set('မှတ်တမ်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။');
        setTimeout(() => this.statusMessage.set(''), 3000);
    } catch (error) {
        console.error("Failed to save report:", error);
        this.statusMessage.set('မှတ်တမ်း သိမ်းဆည်းရာတွင် အမှားအယွင်း ဖြစ်ပေါ်ပါသည်။');
    }
  }

  handleReportRestore(report: Report) {
    if (!confirm('သတိပေးချက်: လက်ရှိလုပ်ဆောင်နေသော စာရင်းများအားလုံး ပျက်သွားပြီး ရွေးချယ်ထားသော မှတ်တမ်းမှ ဒေတာများဖြင့် အစားထိုးသွားပါမည်။ ရှေ့ဆက်ရန် သေချာပါသလား?')) {
      return;
    }

    const type = report.lotteryType;
    this.lotteryType.set(type);
    
    // Normalize mode from report (Eng/Burmese legacy to Current App Standard)
    let targetMode = 'ဒိုင်ကြီး'; // Default fallback
    const lowerMode = (report.mode || '').toLowerCase();
    
    if (lowerMode.includes('agent') || lowerMode.includes('အေးဂျင့်')) targetMode = 'အေးဂျင့်';
    else if (lowerMode.includes('middle') || lowerMode.includes('အလယ်')) targetMode = 'အလယ်ဒိုင်';
    else if (lowerMode.includes('main') || lowerMode.includes('ဒိုင်ကြီး')) targetMode = 'ဒိုင်ကြီး';

    this.activeMode.set(targetMode);
    
    let restoredHistory: HistoryEntry[] = [];

    // Strategy 1: Try to restore from original input history (Best for editing)
    if (report.betHistory && Array.isArray(report.betHistory) && report.betHistory.length > 0) {
        restoredHistory = report.betHistory.map(inputStr => ({
            id: crypto.randomUUID(),
            input: inputStr,
            source: targetMode === 'အေးဂျင့်' ? report.bookieName : 'Restored Report', 
            mode: targetMode
        }));
    } 
    
    // Strategy 2: Fallback to Lottery Data Snapshot if history is missing/empty
    // This handles legacy reports where history wasn't saved correctly but totals exist.
    if (restoredHistory.length === 0 && report.lotteryData) {
        let entries: [string, any][] = [];
        const rawData = report.lotteryData as any;
        
        // Handle different legacy serialization formats (Array vs Object)
        if (Array.isArray(rawData)) {
            entries = rawData;
        } else if (typeof rawData === 'object' && rawData !== null) {
            entries = Object.entries(rawData);
        }

        if (entries.length > 0) {
            // Reconstruct a single bulk input string: "00 500\n01 1000..."
            const lines = entries
                .map(([num, amount]) => `${num} ${Number(amount) || 0}`)
                .filter(line => !line.endsWith(' 0')); // Skip zero amounts
            
            if (lines.length > 0) {
                restoredHistory = [{
                    id: crypto.randomUUID(),
                    input: lines.join('\n'),
                    source: 'Restored from Snapshot',
                    mode: targetMode
                }];
                this.statusMessage.set('မှတ်တမ်းဟောင်း (History) မရှိသဖြင့် ဇယားမှ တိုက်ရိုက်ပြန်လည်ယူထားပါသည်။');
            }
        }
    }

    this.appState.update(current => ({
        ...current,
        [type]: {
            ...current[type],
            betHistory: restoredHistory,
            defaultLimit: report.defaultLimit,
            individualLimits: new Map(report.individualLimits),
            payoutRate: report.payoutRate,
            commissionToPay: report.commissionToPay,
            commissionFromUpperBookie: report.commissionFromUpperBookie,
            agentCommissionFromBookie: report.agentCommissionFromBookie,
            session: report.session || current[type].session,
            drawDate: report.drawDate || current[type].drawDate,
            // Restore bookie name based on targetMode to ensure context consistency
            myAgentName: targetMode === 'အေးဂျင့်' ? report.bookieName : current[type].myAgentName,
            myMiddleBookieName: targetMode === 'အလယ်ဒိုင်' ? report.bookieName : current[type].myMiddleBookieName,
            myMainBookieName: targetMode === 'ဒိုင်ကြီး' ? report.bookieName : current[type].myMainBookieName,
        }
    }));

    this.showReports.set(false);
    
    if (restoredHistory.length > 0) {
        this.statusMessage.set('မှတ်တမ်းကို အောင်မြင်စွာ ပြန်တင်လိုက်ပါပြီ။ ပြင်ဆင်မှုများ ဆက်လက်ပြုလုပ်နိုင်ပါသည်။');
    } else {
        this.statusMessage.set('သတိပေးချက်: ဤမှတ်တမ်းတွင် ဒေတာမရှိပါ။');
    }
    
    setTimeout(() => this.statusMessage.set(''), 4000);
  }

  copyToClipboard(text: string) { if(text) navigator.clipboard.writeText(text); }
  
  copyConfirmationAndClear(): void {
    const msg = this.confirmationMessage();
    if (msg) {
      this.copyToClipboard(msg);
      this.confirmationMessage.set('');
    }
  }

  share(text: string) { if (navigator.share) navigator.share({ text }); else { this.copyToClipboard(text); alert('Copied to clipboard!'); } }

  async backupData(): Promise<void> {
     try {
        this.statusMessage.set('Backup ပြုလုပ်နေသည်...');
        const appData = await this.persistenceService.getAllDataForBackup();
        const licenseData = await this.licenseService.getBackupData();
        
        const fullBackup = {
            appData,
            licenseData,
            backupVersion: '1.0',
            timestamp: new Date().toISOString()
        };

        const jsonString = JSON.stringify(fullBackup, null, 2);
        const blob = new Blob([jsonString], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        const date = new Date().toISOString().split('T')[0];
        a.href = url;
        a.download = `future2d_backup_${date}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        this.statusMessage.set('Backup ကို အောင်မြင်စွာ ပြုလုပ်ပြီးပါပြီ။');
     } catch(e) {
        console.error("Backup failed", e);
        this.statusMessage.set('Backup ပြုလုပ်ရာတွင် အမှားအယွင်း ဖြစ်ပေါ်ပါသည်။');
     } finally {
        setTimeout(() => this.statusMessage.set(''), 4000);
     }
  }

  handleRestore(event: Event): void {
     const file = (event.target as HTMLInputElement).files?.[0];
     if (!file) return;

     if (!confirm('Restore ပြုလုပ်ပါက လက်ရှိဒေတာအားလုံး ပျက်စီးပြီး Backup ဖိုင်ထဲမှ ဒေတာများဖြင့် အစားထိုးသွားမည်ဖြစ်သည်။ ရှေ့ဆက်ရန် သေချာပါသလား?')) {
        (event.target as HTMLInputElement).value = ''; 
        return;
     }

     const reader = new FileReader();
     reader.onload = async (e) => {
        try {
            this.statusMessage.set('Restore ပြုလုပ်နေသည်...');
            const content = e.target?.result as string;
            const backupData = JSON.parse(content);
            
            if (!backupData.appData || !backupData.licenseData) {
                throw new Error('Invalid backup file format.');
            }

            await this.persistenceService.restoreAllData(backupData.appData);
            await this.licenseService.restoreFromBackup(backupData.licenseData);

            this.statusMessage.set('Restore ကို အောင်မြင်စွာ ပြုလုပ်ပြီးပါပြီ။ Application ကို ပြန်လည်စတင်နေသည်...');
            
            setTimeout(() => {
                window.location.reload();
            }, 2000);

        } catch (err) {
            console.error('Failed to restore data', err);
            this.statusMessage.set('Restore ပြုလုပ်ရာတွင် အမှားအယွင်း ဖြစ်ပေါ်ပါသည်။ ဖိုင်ကိုစစ်ဆေးပါ။');
            setTimeout(() => this.statusMessage.set(''), 4000);
        } finally {
            (event.target as HTMLInputElement).value = ''; 
        }
     };
     reader.readAsText(file);
  }

  logout() { this.licenseService.logout(); }
  setAgentSort(sortBy: 'name' | 'sales') { this.agentSortBy.set(sortBy); }

  // --- Over-limit Management Methods ---
  rejectOverLimit(number: string): void {
    const amountToTransfer = this.acknowledgedOverLimits().get(number);
    if (amountToTransfer) {
      this.acknowledgedOverLimits.update(currentMap => {
        const newMap = new Map(currentMap);
        newMap.delete(number);
        return newMap;
      });
      this.acknowledgedHeldOverLimits.update(currentMap => {
        const newMap = new Map(currentMap);
        newMap.set(number, (newMap.get(number) || 0) + amountToTransfer);
        return newMap;
      });
    }

    this.rejectedOverLimits.update(s => {
      const newSet = new Set(s);
      newSet.add(number);
      return newSet;
    });
  }
  reforwardOverLimit(number: string): void {
    const amountToTransfer = this.acknowledgedHeldOverLimits().get(number);
    if (amountToTransfer) {
        this.acknowledgedHeldOverLimits.update(currentMap => {
            const newMap = new Map(currentMap);
            newMap.delete(number);
            return newMap;
        });
        this.acknowledgedOverLimits.update(currentMap => {
            const newMap = new Map(currentMap);
            newMap.set(number, (newMap.get(number) || 0) + amountToTransfer);
            return newMap;
        });
    }
    
    this.rejectedOverLimits.update(s => {
      const newSet = new Set(s);
      newSet.delete(number);
      return newSet;
    });
  }

  private acknowledgeList(list: OverLimitListItem[], mapSignal: WritableSignal<Map<string, number>>, title: string): void {
      if (list.length === 0) return;
      const message = this.formatOverLimitForCopy(list);
      this.copyToClipboard(message);
      this.statusMessage.set(`${title} စာရင်းကို copy ကူးပြီးပါပြီ။`);
      setTimeout(() => this.statusMessage.set(''), 3000);

      const fullOverLimitMap = new Map(this.overLimitCells().map(c => [c.number, c.overLimitAmount]));

      mapSignal.update(currentMap => {
        const newMap = new Map(currentMap);
        list.forEach(item => {
          const totalOverLimit = fullOverLimitMap.get(item.number) || 0;
          newMap.set(item.number, totalOverLimit);
        });
        return newMap;
      });
  }

  acknowledgeAllForwardableOverLimits(): void {
      this.acknowledgeList(this.forwardableOverLimitNumbers(), this.acknowledgedOverLimits, 'အပေါ်ဒိုင်သို့ လွှဲရန်စာရင်း');
  }
  acknowledgeAllHeldOverLimits(): void {
      this.acknowledgeList(this.heldOverLimitNumbers(), this.acknowledgedHeldOverLimits, 'ကိုင်ထားသော ကာသီးစာရင်း');
  }
  acknowledgeMainBookieOverLimits(): void {
      this.acknowledgeList(this.displayedOverLimitNumbers(), this.acknowledgedOverLimits, 'လစ်မစ်ကျော်စာရင်းများ');
  }
  
  formatDate(isoString: string): string {
    if (!isoString) return '';
    return new Date(isoString).toLocaleDateString('en-CA');
  }

  applyProfitSuggestion(): void {
    const suggestion = this.profitOptimizerSuggestion();
    if (!suggestion) return;
  
    const newLimit = this.defaultLimit() + suggestion.suggestedHoldingIncrease;
    this.updateCurrentState('defaultLimit', newLimit);
  
    this.suggestionAppliedRecently.set(true);
    this.statusMessage.set('Default Limit ကို အကြံပြုချက်အတိုင်း အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။');
    setTimeout(() => this.statusMessage.set(''), 3000);
  }
  
  dismissProfitSuggestion(): void {
    this.profitOptimizerSuggestion.set(null);
    this.suggestionAppliedRecently.set(false);
  }

  showSuggestionPanelAgain(): void {
    this.suggestionAppliedRecently.set(false);
  }

  private formatOverLimitForCopy(list: OverLimitListItem[]): string {
      if (!list || list.length === 0) return '';

      const header = `--- ${this.bookieName()} ---`;
      
      const today = new Date().toLocaleDateString('en-CA');
      let dateLine = `နေ့စွဲ: ${today}`;
      if (this.lotteryType() === '2D') {
          const sessionText = this.session() === 'morning' ? 'မနက်ပိုင်း' : 'ညနေပိုင်း';
          dateLine += ` (${sessionText})`;
      }

      const separator = '--------------------';
      
      const totalAmount = list.reduce((sum, item) => sum + item.overLimitAmount, 0);
      const totalCount = list.length;

      const bodyParts: string[] = [];
      list.forEach((item, index) => {
          bodyParts.push(`${item.number} = ${item.overLimitAmount}`);
          if ((index + 1) % 10 === 0 && (index + 1) < list.length) {
              bodyParts.push(separator);
          }
      });
      const body = bodyParts.join('\n');
      
      const footer = `စုစုပေါင်း (${totalCount}) ကွက်: ${totalAmount.toLocaleString()} ${this.currencySymbol()}`;

      return `${header}\n${dateLine}\n${separator}\n${body}\n${separator}\n${footer}`;
  }

  // --- Bet Detail Modal Methods ---
  openBetDetailModal(number: string): void {
    if ((this.lotteryData().get(number) || []).length === 0) return;
    this.selectedNumberForDetail.set(number);
    this.showBetDetailModal.set(true);
  }
  closeBetDetailModal(): void {
    this.showBetDetailModal.set(false);
    this.selectedNumberForDetail.set(null);
  }
  editBetFromDetail(betToEdit: BetDetail): void {
    const historyEntry = this.betHistory().find(h => h.id === betToEdit.historyEntryId);
    if (historyEntry) this.editHistoryEntry(historyEntry);
    this.closeBetDetailModal();
  }
  deleteBetFromDetail(betToDelete: BetDetail): void {
    const historyEntry = this.betHistory().find(h => h.id === betToDelete.historyEntryId);
    if (historyEntry) {
        if (confirm(`"${historyEntry.input}" ဟူသော စာရင်းတစ်ခုလုံးကို ဖျက်ရန် သေချာပါသလား?`)) {
            this.deleteHistoryEntry(historyEntry.id);
        }
    }
    this.closeBetDetailModal();
  }

  handleForwardingModalClose(assignments: Assignments | null): void {
    this.isForwardingModalOpen.set(false);
    if (assignments) {
        const assignedNumbers = new Set<string>();
        Object.values(assignments).forEach(betList => {
            betList.forEach(bet => assignedNumbers.add(bet.number));
        });
        
        const fullOverLimitMap = new Map(this.overLimitCells().map(c => [c.number, c.overLimitAmount]));

        this.acknowledgedOverLimits.update(currentMap => {
            const newMap = new Map(currentMap);
            assignedNumbers.forEach(number => {
                const totalOverLimit = Number(fullOverLimitMap.get(number) || 0);
                if (totalOverLimit > 0) {
                    newMap.set(number, totalOverLimit);
                }
            });
            return newMap;
        });

        this.statusMessage.set('ကာသီးစာရင်းများကို အောင်မြင်စွာ ခွဲဝေပြီးပါပြီ။');
        setTimeout(() => this.statusMessage.set(''), 3000);
    }
  }

  // --- Voucher Functions ---
  openVoucherModal(): void {
    if (this.pendingSubmissions().length === 0) return;

    const allBets: { number: string; amount: number }[] = [];
    const pending = this.pendingSubmissions();
    for (const input of pending) {
        const bets = this.betParsingService.parseRaw(input, this.lotteryType());
        allBets.push(...bets);
    }

    if (allBets.length === 0) {
        this.statusMessage.set('ဘောင်ချာထုတ်ရန် စာရင်းမရှိပါ။');
        setTimeout(() => this.statusMessage.set(''), 2000);
        return;
    }

    const totalAmount = allBets.reduce((sum, b) => sum + b.amount, 0);
    const date = new Date().toLocaleDateString('en-CA');
    const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

    this.voucherData.set({
        items: allBets,
        totalAmount,
        totalCount: allBets.length,
        date,
        time,
        currency: this.currencySymbol(),
        settings: this.voucherSettings()
    });
    this.showVoucherModal.set(true);
  }

  printVoucher(): void {
    window.print();
  }

  closeVoucherModal(): void {
    this.showVoucherModal.set(false);
    this.voucherData.set(null);
  }

  saveVoucherSettings() {
      const type = this.lotteryType();
      this.appState.update(current => ({
          ...current,
          [type]: {
              ...current[type],
              voucherSettings: this.voucherSettings()
          }
      }));
      this.showVoucherSettings.set(false);
  }
}
